### PR TITLE
Flying Sphinx Resque Deltas

### PR DESCRIPTION
**Pull request by pat**
Hi Aaron

As you may have noticed from other emails, I've whipped up resque delta support for Flying Sphinx (a Sphinx/Thinking Sphinx add-on for Heroku I run). It's a little different to the standard delta approaches, as the Sphinx command line tools aren't available, so the `flying-sphinx` gem does the hard work.

It'd be great if you could merge this in! If there's anything missing or unclear, let me know.

Thanks

Pat

### CODE REVIEW

**Comment by agibralter** [comment]
Hey Pat,

Sounds great! I'm out of town for the next few days but I'll try to merge it
asap.

Thanks,
Aaron

**Comment by pat** [comment]
No worries, there's no urgency :)

Pat

**Comment by agibralter** [comment]
Hey Pat,

Sorry for the delay! I'm finally back in action.

Anyway, so I'm just looking through the Pull. Everything looks good! So... `FlyingSphinx::ResqueDelta::DeltaJob` inherits from `ThinkingSphinx::Deltas::ResqueDelta::DeltaJob` so that the locking mechanisms get used for FlyingSphinx?

**Comment by pat** [comment]
I don't have my head around the locking side of things - the existing rake tasks won't be used - but if whatever's in the underlying `ThinkingSphinx::Deltas::ResqueDelta::DeltaJob` does the trick, then should be fine :)

**Comment by agibralter** [comment]
Would you mind taking a closer look at https://github.com/agibralter/ts-resque-delta/blob/master/lib/thinking_sphinx/deltas/resque_delta/tasks.rb -- I have a hunch that FlyingSphinx can benefit from the same locking logic that we added to ts-resque-delta; in particular, see how ts-resque-delta enhances/wraps the existing thinking-sphinx rake tasks with locking behavior? I think we could use the same logic in FlyingSphinx to ensure that `indexer` isn't operating on the core and delta of a single model at the same time. Finally, I think that FlyingSphinx can use "smart" indexing:

Instead of this for `FlyingSphinx::ResqueDelta::DeltaJob.perform`:

``` ruby
# ...
FlyingSphinx::IndexRequest.new(indices).perform
# ...
```

It could be something like:

``` ruby
# ...
indices.each do |index|
  # lock
  FlyingSphinx::IndexRequest.new([index]).perform
  # unlock
end
# ...
```

**Comment by agibralter** [comment]
Any thoughts on my last comment?

**Comment by pat** [comment]
Sorry Aaron, been pretty busy lately, and I've not had any real experience using Resque/Redis. Your comment is still in my to-do list, but if you find some time and want to investigate I won't complain :)

**Comment by agibralter** [comment]
Ok, really sorry this has taken so long! Please disregard my comment from July 22. It's really missing the point -- I don't know what I was thinking when I wrote it.

Anyway, my concern about locking has to do with indexing the cores (as opposed to the deltas), and all that logic is in the rake task `rake thinking_sphinx:smart_index`:

``` ruby

  desc 'Like `rake thinking_sphinx:index`, but locks one index at a time.'
  task :smart_index => :app_env do
    # Load config like ts:in.
    @ts_config = ThinkingSphinx::Configuration.instance
    unless ENV['INDEX_ONLY'] == 'true'
      puts "Generating Configuration to #{@ts_config.config_file}"
      @ts_config.build
    end
    FileUtils.mkdir_p(@ts_config.searchd_file_path)

    # Index each core, one at a time. Wrap with delta locking logic.
    sphinx_indexes.each do |index_name|
      lock_delta(index_name)
      @ts_config.controller.index("#{index_name}_core", :verbose => true)
      ret = $?
      unlock_delta(index_name)
      exit(-1) if ret.to_i != 0
      Resque.enqueue(
        ThinkingSphinx::Deltas::ResqueDelta::DeltaJob,
        ["#{index_name}_delta"]
      )
    end
  end
```

The idea here (introduced by Todd Fisher/@taf2) is that there is no point in updating the delta indexes when re-indexing the cores. Also, since some cores might take a long time to index, it does not make sense to lock all the models' delta indexes at once. I'm guessing this type of logic could be introduced into the FlyingSphinx gem... but I don't think it's _required_.

I'll merge this FlyingSphinx stuff in now and release a new gem; however, I think it might make sense to consider the "smart indexing" at some point for FlyingSphinx.

**Comment by agibralter** [comment]
Question is... what version should this release be? Do you think FlyingSphinx support means we should bump to 2.0.0?

**Comment by pat** [comment]
1.1.0 sounds right to me - you've not shaken things up and changed the way people have to use the library, just added extra functionality.

**Pull request merged**
