### PR TITLE
Use transaction

### PR DESCRIPTION
**Pull request by ryansch**
This adds one commit on top of the updated test suite commit.  It's intended to be merged after #16.

I was realizing that we could drop the contents of the temp set if we're interrupted before we merge the temp set and processing set together.  I fixed this by wrapping the method in a redis transaction.

### CODE REVIEW

**Comment by agibralter** [comment]
So I added you as a collaborator and merged the other pull request you submitted. This one commit that's identical to the other pull request, but seems like it will merge cleanly anyway.

Were you having issues with race conditions?

**Comment by ryansch** [comment]
I'll fix this pull request and push it back to you for review.  Sorry about that!

I haven't hit this race condition in production to my knowledge.  I was upgrading our app to use redis-rb 3.0 and I needed to audit all uses of redis to make sure we were compatible with the new API.  I discovered this during that audit.

**Comment by ryansch** [comment]
Rebased against master.  Let me know what you think.

**Comment by ryansch** [comment]
I've also been running this in production without issue for about a week.

I'm using it with my resque fork: https://github.com/aceofsales/resque
I've added a few patches that have been sitting in the queue for a while.

**Comment by ryansch** [comment]
Merged as per our email discussion.

**Pull request merged**
