### PR TITLE
Support for thinking_sphinx 3, rails 4.0.0.beta1, ruby 2.0.0p0

### PR DESCRIPTION
**Pull request by atlantis**
1) @ts_config.generate/@ts_config.configuration no longer necessary
2) thinking_sphinx namespace is gone in favor of ts (see https://github.com/pat/thinking-sphinx/issues/468)
3) apparently ts:reindex isn't a valid rake task anymore 

Thanks!
James Hill

### CODE REVIEW

**Comment by agibralter** [comment]
So it looks like I should start a 2.x branch of ts-resque-delta. Is this all that is required to have ts-resque-delta work with TS v3?

**Comment by mpotter** [comment]
@agibralter for what it's worth, I just tested this fork on a Rails 4.0.0.beta1 app running ruby 2.0.0p0 and delta jobs are not being queued in Resque.

Referencing the [edge branch](https://github.com/pat/ts-delayed-delta/tree/edge) of ts-delayed-delta seems to reveal that the delta API for the `index` method changed: [ts-resque-delta](https://github.com/agibralter/ts-resque-delta/blob/master/lib/thinking_sphinx/deltas/resque_delta.rb#L85) vs. [ts-delayed-delta edge](https://github.com/pat/ts-delayed-delta/blob/edge/lib/thinking_sphinx/deltas/delayed_delta.rb#L48)

I'm not too familiar with either codebase so I could be off... @atlantis is this working for you?

**Comment by atlantis** [comment]
Sorry, should have been more clear… those were the changes necessary to start a rails 4 app successfully with ts-resque-delta + ts 3.  Still lots of work to do - in addition to not actually working, I haven't updated the gem spec/tests for AR 4.  

I'd be happy to redact this pull request and try again once I've made more progress… I'm new to both ruby and open source style development, so any and all suggestions are welcome!

**Comment by atlantis** [comment]
@agibralter got basic functionality working today... quick question: does ThinkingSphinx handle deleted records automatically now (ref https://groups.google.com/forum/?fromgroups=#!topic/thinking-sphinx/_fGTfqJXog0)?

If so, can I remove ThinkingSphinx::Deltas::ResqueDelta::FlagAsDeletedSet?

**Comment by ryansch** [comment]
@agibralter I haven't been tracking the TS updates; we've moved to Elasticsearch after outgrowing Sphinx again for our volume of data.  Let me know if you want me to dig in to any of this.

**Comment by agibralter** [comment]
@atlantis Sorry for the delay. Yeah, in general pull requests are best if they are "complete" features or changes. No need to close this one; we can discuss and evaluate your commits. I really haven't had too much time to look into TS v3 and I'm not sure when I will. I know @pat mentioned that he was thinking about changing the default delta behavior. I was thinking about waiting to see what happens in TS before making changes to ts-resque-delta.

**Comment by agibralter** [comment]
@ryansch Ah interesting–what was the main pain point that prompted the switch? How have you been finding ElasticSearch compared to Sphinx? Any good ruby libraries for it? (Sorry for all the questions!)

**Comment by ryansch** [comment]
@agibralter I've been finding ES vastly superior to Sphinx.
- It's fairly easy to set up a cluster with chef.
- It scales amazingly well so you can throw more hardware at it.
- Because it runs across more than one machine it's much more highly available.
- It can index new records in near realtime so there's no need for delta indexing.
- Search queries are faster and there's a lot more power there.
- Tire (https://github.com/karmi/tire) is a wonderful ruby library for interfacing with it.

We've gone from being a fairly large Sphinx user to being quite a small ElasticSearch user.  Do beware: It takes quite a bit of learning to get ES to dance for you.  It's not nearly as turnkey but it's worth it.

**Comment by morganick** [comment]
Other points to add:
- Reduces our MySQL db load (No deltas running in the background)
- Not confined to the columns in the table you are searching. (We can serialize data from anywhere into a document that is indexed by ES.)

We currently have ~45gb of data consisting of > 60 million documents.

**Comment by ryansch** [comment]
To be clear: I work with @morganick

**Comment by agibralter** [comment]
@ryansch @morganick thank you! :) One last question–is it tough to change up how your data is structured once you get started?

(I guess this isn't the best place for a convo on ES vs. Sphinx but, hey, why not have it be in public.)

**Comment by ryansch** [comment]
No it's not hard.  Make sure you use index aliases because you will mess up at least once.  Aliases make it easy to start a new index and rotate it in place of an old one.

**Comment by morganick** [comment]
Can take a while to build the new index depending on the size.

The thing that takes the longest to wrap your head around is how to properly index your data. The defaults are pretty good but fine tuning the index will make it blazing fast.

There is much more to this topic. It would be well worth your time to experiment and dig in.

**Comment by pat** [comment]
Closing this, as it covers the same work as #25, which has been merged and will be released as v2.0.0 shortly.

**Pull request closed without merging**
